# Exploratory data analysis - obesity

In [1]:
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
# usando path para facilitar acesso a arquivos
caminho_arquivo = Path('clean_new_data_obesity.csv').resolve().parents[1]
print('caminho do diretório',caminho_arquivo)

caminho do diretório D:\python\bellabeat-analysis

In [ ]:

df = pd.read_csv(f'{caminho_arquivo}/database/obesity-data/clean_new_data_obesity.csv', sep =',')

In [4]:
df.head(4)

,Gender,Age,Height (cm),Overweight_Family,Consumption_of_Fast_Food,Frequency_of_Consuming_Vegetables,Number_of_Main_Meals_Daily,Food_Intake_Between_Meals,Smoking,Liquid_Intake_Daily,Calculation_of_Calorie_Intake,Weekly_Physical_Activity,Schedule_Dedicated_to_Technology,Type_of_Transportation_Used,BMI_Category,BMI_Category_Summary
0,Female,18,155,No,No,3-Always,1,3-Usually,No,Less than a liter,No,3-4 days,5+ hours,Public transportation,Normal weight,Under or normal weight
1,Female,18,158,No,No,3-Always,1,1-Rarely,No,Less than a liter,No,No physical activity,5+ hours,Bike,Normal weight,Under or normal weight
2,Female,18,159,No,No,2-Sometimes,1,3-Usually,No,More than 2 liters,No,1-2 days,5+ hours,Public transportation,Normal weight,Under or normal weight
3,Female,18,162,No,No,2-Sometimes,2,2-Sometimes,No,1 to 2 liters,No,No physical activity,5+ hours,Public transportation,Normal weight,Under or normal weight

## Análise exercício vs peso

In [5]:
df['Gender'].value_counts()

Gender
Female    898
Male      712
Name: count, dtype: int64

In [6]:
df_female = df.loc[df['Gender']== 'Female']

In [8]:
pd.pivot_table(df_female, values= ['Age'] , index= ['Weekly_Physical_Activity'], columns= ['BMI_Category'], aggfunc= 'count')

                                   Age
BMI_Category             Normal weight Obese Overweight Underweight
Weekly_Physical_Activity
1-2 days                         111.0  22.0       23.0        12.0
3-4 days                         141.0  15.0       48.0         4.0
5-6 days                          93.0  33.0       76.0         NaN
7 days                            56.0  60.0       72.0         NaN
No physical activity              69.0   5.0       15.0        43.0

In [9]:
pd.pivot_table(df_female, values= ['Age'] , index= ['Liquid_Intake_Daily'], columns= ['BMI_Category'], aggfunc= 'count')

                              Age
BMI_Category        Normal weight Obese Overweight Underweight
Liquid_Intake_Daily
1 to 2 liters                 148    56         86          18
Less than a liter             123    38         49          32
More than 2 liters            199    41         99           9